{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "d002a579-cf28-4589-bf4b-3d0061d5a0ed",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-11-06 11:40:05.567 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-06 11:40:05.571 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-06 11:40:05.573 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-06 11:40:05.578 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-06 11:40:05.580 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-06 11:40:05.583 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-06 11:40:05.587 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-06 11:40:05.589 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-06 11:40:05.591 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-06 11:40:05.595 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-06 11:40:05.597 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-06 11:40:05.600 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-06 11:40:05.602 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-06 11:40:05.604 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-06 11:40:05.607 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-06 11:40:05.611 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-06 11:40:05.614 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-06 11:40:05.619 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-06 11:40:05.622 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-06 11:40:05.625 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-06 11:40:05.629 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-06 11:40:05.633 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-06 11:40:05.636 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-06 11:40:05.639 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-06 11:40:05.642 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-06 11:40:05.648 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-06 11:40:05.652 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-06 11:40:05.655 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-06 11:40:05.658 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-06 11:40:05.661 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-11-06 11:40:05.664 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    }
   ],
   "source": [
    "import streamlit as st\n",
    "import random\n",
    "\n",
    "def martingale(balance, bet_size, spins):\n",
    "    results = []\n",
    "    for spin in range(spins):\n",
    "        bet = bet_size\n",
    "        while balance >= bet:\n",
    "            win = (random.randint(0,36) % 2 == 0 and random.randint(0,36) != 0)\n",
    "            if win:\n",
    "                balance += bet\n",
    "                results.append({'Spin': spin+1, 'Bet': bet, 'Result': 'Win', 'Balance': balance})\n",
    "                break\n",
    "            else:\n",
    "                balance -= bet\n",
    "                results.append({'Spin': spin+1, 'Bet': bet, 'Result': 'Loss', 'Balance': balance})\n",
    "                bet *= 2\n",
    "                if balance < bet:\n",
    "                    break\n",
    "    return results\n",
    "\n",
    "def paroli(balance, bet_size, spins, prog_limit=3):\n",
    "    results = []\n",
    "    win_streak = 0\n",
    "    bet = bet_size\n",
    "    for spin in range(spins):\n",
    "        if balance < bet:\n",
    "            results.append({'Spin': spin+1, 'Bet': bet, 'Result': 'Insufficient funds', 'Balance': balance})\n",
    "            break\n",
    "        win = (random.randint(0,36) % 2 == 0 and random.randint(0,36) != 0)\n",
    "        if win:\n",
    "            balance += bet\n",
    "            results.append({'Spin': spin+1, 'Bet': bet, 'Result': 'Win', 'Balance': balance})\n",
    "            win_streak += 1\n",
    "            if win_streak == prog_limit:\n",
    "                bet = bet_size\n",
    "                win_streak = 0\n",
    "            else:\n",
    "                bet *= 2\n",
    "        else:\n",
    "            balance -= bet\n",
    "            results.append({'Spin': spin+1, 'Bet': bet, 'Result': 'Loss', 'Balance': balance})\n",
    "            bet = bet_size\n",
    "            win_streak = 0\n",
    "    return results\n",
    "\n",
    "def fibonacci(balance, bet_size, spins):\n",
    "    fib = [bet_size, bet_size]\n",
    "    for _ in range(20):\n",
    "        fib.append(fib[-1] + fib[-2])\n",
    "    pos = 1\n",
    "    results = []\n",
    "    for spin in range(spins):\n",
    "        bet = fib[pos] if pos < len(fib) else bet_size\n",
    "        if balance < bet:\n",
    "            results.append({'Spin': spin+1, 'Bet': bet, 'Result': 'Insufficient funds', 'Balance': balance})\n",
    "            break\n",
    "        win = (random.randint(0,36) % 2 == 0 and random.randint(0,36) != 0)\n",
    "        if win:\n",
    "            balance += bet\n",
    "            pos = max(pos-2, 1)\n",
    "            results.append({'Spin': spin+1, 'Bet': bet, 'Result': 'Win', 'Balance': balance})\n",
    "        else:\n",
    "            balance -= bet\n",
    "            pos += 1\n",
    "            results.append({'Spin': spin+1, 'Bet': bet, 'Result': 'Loss', 'Balance': balance})\n",
    "    return results\n",
    "\n",
    "st.title(\"Roulette Strategy Simulator\")\n",
    "\n",
    "strategy = st.selectbox(\"Choose Strategy\", [\"Martingale\", \"Paroli\", \"Fibonacci\"])\n",
    "balance = st.number_input(\"Starting Balance\", min_value=1, value=500, step=1)\n",
    "bet_size = st.number_input(\"Betting Unit Size\", min_value=1, value=5, step=1)\n",
    "spins = st.number_input(\"Number of Spins\", min_value=1, value=50, step=1)\n",
    "prog_limit = 3\n",
    "if strategy == \"Paroli\":\n",
    "    prog_limit = st.number_input(\"Paroli Progression Limit\", min_value=1, value=3, step=1)\n",
    "\n",
    "if st.button(\"Run Simulation\"):\n",
    "    if strategy == \"Martingale\":\n",
    "        results = martingale(balance, bet_size, spins)\n",
    "    elif strategy == \"Paroli\":\n",
    "        results = paroli(balance, bet_size, spins, prog_limit)\n",
    "    else:\n",
    "        results = fibonacci(balance, bet_size, spins)\n",
    "    st.write(\"Simulation Results:\")\n",
    "    st.dataframe(results)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "8339a3b7-780b-4a31-9025-0de8edd8620c",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
